version: "3.8"

services:

###################################################################
# Dependencies
  minio:
    image: minio/minio:latest
    container_name: minio-server
    env_file:
      - ./.env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-localtrack}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-ReplaceMePassword}
    volumes:
      - ${DATA_DIR}/minio_data:/minio_data
    command: server --console-address ":9001" /minio_data
    networks:
      - minio-net

###################################################################
#  Setup Minio
  create-bucket:
    image: minio/mc:RELEASE.2023-09-22T05-07-46Z
    container_name: create-bucket
    depends_on:
      - minio
    env_file:
      - ./.env
    networks:
      - minio-net
    entrypoint: >
      /bin/sh -c "
      mc alias set fastapi http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb --ignore-existing fastapi/${ROOT_BUCKET_NAME}/${MODEL_BUCKET_NAME};
      mc mb --ignore-existing fastapi/${ROOT_BUCKET_NAME}/${TRACK_BUCKET_NAME};
      mc mb --ignore-existing fastapi/${ROOT_BUCKET_NAME}/${VIDEO_BUCKET_NAME};
      mc admin user add fastapi ${MINIO_LIVE_ACCESS_KEY} ${MINIO_LIVE_SECRET_KEY};
      mc admin policy list fastapi;
      mc admin policy attach fastapi readwrite --user ${MINIO_LIVE_ACCESS_KEY};
      exit 0;
      "
networks:
  minio-net:
    external: true