version: "3.8"

services:

###################################################################
# Minio Dependency
###################################################################
  minio:
    image: minio/minio:latest
    container_name: minio-server
    hostname: minio
    env_file:
      - ./.env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-localtrack}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-ReplaceMePassword}
    volumes:
      - ${DATA_DIR}/minio_data:/minio_data
    command: server --console-address ":9001" /minio_data
    networks:
      - minio-net
###################################################################
# Services
###################################################################
  fastapi:
    image: mbari/fastapi-localtrack:${GIT_VERSION}
    container_name: fastapi-localtrack
    env_file:
      - ./.env
    ports:
      - "8000:80"
    networks:
      - minio-net
  daemon:
    image: mbari/fastapi-localtrack-daemon:${GIT_VERSION}
    container_name: fastapi-localtrack-daemon
    env_file:
      - ./.env
    environment:
      - NOTIFY_URL=${NOTIFY_URL}
      - MODEL_DIR=/models
      - DATABASE_DIR=/sqlite_data
    volumes:
      - ${DATA_DIR}/sqlite_data:/sqlite_data
      - ${DATA_DIR}/models:/models
    networks:
      - minio-net
    restart: always
###################################################################
#  Setup Minio
###################################################################
  mc-minio:
    image: minio/mc:RELEASE.2023-09-22T05-07-46Z
    container_name: setup-minio
    depends_on:
      - minio
    env_file:
      - ./.env
    networks:
      - minio-net
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb --ignore-existing myminio/${ROOT_BUCKET_NAME}/${MODEL_PREFIX};
      mc mb --ignore-existing myminio/${ROOT_BUCKET_NAME}/${TRACK_PREFIX};
      mc admin user add myminio fastapi ${MINIO_LIVE_ACCESS_KEY};
      mc admin policy list myminio;
      mc admin policy attach myminio readwrite --user fastapi; 
      curl -O https://902005-public.s3.us-west-2.amazonaws.com/models/Megadetector/best.pt;
      curl -O https://902005-public.s3.us-west-2.amazonaws.com/models/track-config/strong_sort_benthic.yaml;
      mc cp strong_sort_benthic.yaml ${ROOT_BUCKET_NAME}/${MODEL_PREFIX}/track-config/strong_sort_benthic.yaml;
      mc cp best.pt myminio/${ROOT_BUCKET_NAME}/${MODEL_PREFIX}/MegadetectorTest.pt;
      exit 0;
      "
    volumes:
      - ${DATA_DIR}/objects:/data

networks:
  minio-net:
    external: true