database:
  path: "./sqlite_data"

defaults:
  args: --conf-thres=0.01 --iou-thres=0.4 --max-det=100 --agnostic-nms --imgsz 640 --reid-url=https://902005-public.s3.us-west-2.amazonaws.com/training/reid/benthic2017/osnet_ain_x0_75.pth.tar
  video_url: http://localhost:8090/video/V4361_20211006T162656Z_h265_10frame.mp4

monitors:
  models:
    path: "./models"
    check_every: 60

  docker:
    check_every: 15
    strongsort_container_arm64: mbari/strongsort-yolov5:arm64-d83ee6a
    strongsort_container: mbari/strongsort-yolov5:d83ee6a

minio:
  endpoint: "localhost:9000"
  root_bucket: localtrack
  model_prefix: models
  track_prefix: tracks
  video_prefix: video

aws_public:
  model: s3://902005-public/models/yolov5x_mbay_benthic_model.tar.gz
