name: Run pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run nginx Docker container to serve test data
        run: docker run --rm -d -p 8090:80 -v tests/data:/data:ro --name microtrack-nginx mbari/nginx

      - name: Wait for Docker container to start
        run: sleep 10

      - name: Setup environment
        run: |
          export AWS_DEFAULT_PROFILE=minio-localtrack

      - name: Run daemon module to handle processing test data
        working-directory: src
        run: python -m daemon

      - name: Run pytest
        run: pytest
